# Generated by Django 5.2.17 on 2026-09-14 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=100)),
                ('started_since', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
